// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Railway.Api.Models;

#nullable disable

namespace Railway.Api.Migrations
{
    [DbContext(typeof(DatabaseProjectContext))]
    partial class DatabaseProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Railway.Api.Models.Cargocontainer", b =>
                {
                    b.Property<int>("ContainerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ContainerID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ContainerId"));

                    b.Property<string>("ContainerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int")
                        .HasColumnName("ShipmentID");

                    b.HasKey("ContainerId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ShipmentId" }, "ShipmentID");

                    b.ToTable("cargocontainer", (string)null);
                });

            modelBuilder.Entity("Railway.Api.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CountryID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CountryId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "Name")
                        .IsUnique();

                    b.ToTable("country", (string)null);
                });

            modelBuilder.Entity("Railway.Api.Models.Customsclearance", b =>
                {
                    b.Property<int>("ClearanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClearanceID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ClearanceId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int")
                        .HasColumnName("ShipmentID");

                    b.Property<int>("StationId")
                        .HasColumnType("int")
                        .HasColumnName("StationID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ClearanceId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ShipmentId" }, "ShipmentID")
                        .HasDatabaseName("ShipmentID1");

                    b.HasIndex(new[] { "StationId" }, "StationID");

                    b.ToTable("customsclearance", (string)null);
                });

            modelBuilder.Entity("Railway.Api.Models.Dependent", b =>
                {
                    b.Property<int>("PassengerId")
                        .HasColumnType("int")
                        .HasColumnName("PassengerID");

                    b.Property<int>("DependentId")
                        .HasColumnType("int")
                        .HasColumnName("DependentID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("PassengerId", "DependentId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.ToTable("dependent", (string)null);
                });

            modelBuilder.Entity("Railway.Api.Models.Freightshipment", b =>
                {
                    b.Property<int>("ShipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ShipmentID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ShipmentId"));

                    b.Property<string>("Shipper")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TrainId")
                        .HasColumnType("int")
                        .HasColumnName("TrainID");

                    b.Property<decimal>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ShipmentId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TrainId" }, "TrainID");

                    b.ToTable("freightshipment", (string)null);
                });

            modelBuilder.Entity("Railway.Api.Models.Freighttrain", b =>
                {
                    b.Property<int>("TrainId")
                        .HasColumnType("int")
                        .HasColumnName("TrainID");

                    b.Property<decimal>("MaxCargoWeight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("TrainId")
                        .HasName("PRIMARY");

                    b.ToTable("freighttrain", (string)null);
                });

            modelBuilder.Entity("Railway.Api.Models.Loyaltyaccount", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("Class")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValueSql("'Bronze'");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int")
                        .HasColumnName("PassengerID");

                    b.Property<int?>("TotalMiles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("AccountId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PassengerId" }, "PassengerID")
                        .IsUnique();

                    b.ToTable("loyaltyaccount", (string)null);
                });

            modelBuilder.Entity("Railway.Api.Models.Luggage", b =>
                {
                    b.Property<int>("LuggageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LuggageID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LuggageId"));

                    b.Property<int>("ReservationId")
                        .HasColumnType("int")
                        .HasColumnName("ReservationID");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("LuggageId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ReservationId" }, "ReservationID");

                    b.ToTable("luggage", (string)null);
                });

            modelBuilder.Entity("Railway.Api.Models.Maintenancerecord", b =>
                {
                    b.Property<int>("MaintenanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaintenanceID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaintenanceId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TrackId")
                        .HasColumnType("int")
                        .HasColumnName("TrackID");

                    b.Property<int?>("TrainId")
                        .HasColumnType("int")
                        .HasColumnName("TrainID");

                    b.HasKey("MaintenanceId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TrackId" }, "TrackID");

                    b.HasIndex(new[] { "TrainId" }, "TrainID")
                        .HasDatabaseName("TrainID1");

                    b.ToTable("maintenancerecord", (string)null);
                });

            modelBuilder.Entity("Railway.Api.Models.Passenger", b =>
                {
                    b.Property<int>("PassengerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PassengerID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PassengerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("PassengerId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "Email")
                        .IsUnique();

                    b.ToTable("passenger", (string)null);
                });

            modelBuilder.Entity("Railway.Api.Models.Passengertrain", b =>
                {
                    b.Property<int>("TrainId")
                        .HasColumnType("int")
                        .HasColumnName("TrainID");

                    b.Property<int>("PassengerCapacity")
                        .HasColumnType("int");

                    b.HasKey("TrainId")
                        .HasName("PRIMARY");

                    b.ToTable("passengertrain", (string)null);
                });

            modelBuilder.Entity("Railway.Api.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReservationID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int")
                        .HasColumnName("PassengerID");

                    b.Property<string>("ReservationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("ScheduleID");

                    b.HasKey("ReservationId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PassengerId" }, "PassengerID")
                        .HasDatabaseName("PassengerID1");

                    b.HasIndex(new[] { "ScheduleId" }, "ScheduleID");

                    b.ToTable("reservation", (string)null);
                });

            modelBuilder.Entity("Railway.Api.Models.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RouteID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RouteId"));

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("RouteId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RouteName" }, "RouteName")
                        .IsUnique();

                    b.ToTable("route", (string)null);
                });

            modelBuilder.Entity("Railway.Api.Models.Routestop", b =>
                {
                    b.Property<int>("RouteId")
                        .HasColumnType("int")
                        .HasColumnName("RouteID");

                    b.Property<int>("StationId")
                        .HasColumnType("int")
                        .HasColumnName("StationID");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.HasKey("RouteId", "StationId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "StationId" }, "StationID")
                        .HasDatabaseName("StationID1");

                    b.ToTable("routestop", (string)null);
                });

            modelBuilder.Entity("Railway.Api.Models.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SeatID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SeatId"));

                    b.Property<string>("CoachType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int")
                        .HasColumnName("ReservationID");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("SeatId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ReservationId" }, "ReservationID")
                        .HasDatabaseName("ReservationID1");

                    b.ToTable("seat", (string)null);
                });

            modelBuilder.Entity("Railway.Api.Models.Sensor", b =>
                {
                    b.Property<int>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SensorId"));

                    b.Property<string>("SensorName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SensorType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TrainId")
                        .HasColumnType("int");

                    b.HasKey("SensorId");

                    b.HasIndex("TrainId");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("Railway.Api.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StaffID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("StaffId")
                        .HasName("PRIMARY");

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("Railway.Api.Models.Staffassignment", b =>
                {
                    b.Property<int>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("StaffID");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("ScheduleID");

                    b.Property<DateOnly>("AssignmentDate")
                        .HasColumnType("date");

                    b.HasKey("StaffId", "ScheduleId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "ScheduleId" }, "ScheduleID")
                        .HasDatabaseName("ScheduleID1");

                    b.ToTable("staffassignment", (string)null);
                });

            modelBuilder.Entity("Railway.Api.Models.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StationID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StationId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("CountryID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("StationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("StationId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CountryId" }, "CountryID");

                    b.ToTable("station", (string)null);
                });

            modelBuilder.Entity("Railway.Api.Models.Tracksegment", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TrackID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TrackId"));

                    b.Property<decimal>("Distance")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("EndStationId")
                        .HasColumnType("int")
                        .HasColumnName("EndStationID");

                    b.Property<int>("MaxFreightSpeed")
                        .HasColumnType("int");

                    b.Property<int>("MaxPassengerSpeed")
                        .HasColumnType("int");

                    b.Property<int>("StartStationId")
                        .HasColumnType("int")
                        .HasColumnName("StartStationID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TrackId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EndStationId" }, "EndStationID");

                    b.HasIndex(new[] { "StartStationId" }, "StartStationID");

                    b.ToTable("tracksegment", (string)null);
                });

            modelBuilder.Entity("Railway.Api.Models.Train", b =>
                {
                    b.Property<int>("TrainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TrainID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TrainId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TrainType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TrainId")
                        .HasName("PRIMARY");

                    b.ToTable("train", (string)null);
                });

            modelBuilder.Entity("Railway.Api.Models.Trainschedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ScheduleID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("DepartureTime")
                        .HasColumnType("time");

                    b.Property<int>("RouteId")
                        .HasColumnType("int")
                        .HasColumnName("RouteID");

                    b.Property<int>("TrainId")
                        .HasColumnType("int")
                        .HasColumnName("TrainID");

                    b.HasKey("ScheduleId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RouteId" }, "RouteID");

                    b.HasIndex(new[] { "TrainId" }, "TrainID")
                        .HasDatabaseName("TrainID2");

                    b.ToTable("trainschedule", (string)null);
                });

            modelBuilder.Entity("Railway.Api.Models.Waitinglist", b =>
                {
                    b.Property<int>("WaitlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WaitlistID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WaitlistId"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int")
                        .HasColumnName("PassengerID");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("ScheduleID");

                    b.HasKey("WaitlistId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PassengerId" }, "PassengerID")
                        .HasDatabaseName("PassengerID2");

                    b.HasIndex(new[] { "ScheduleId" }, "ScheduleID")
                        .HasDatabaseName("ScheduleID2");

                    b.ToTable("waitinglist", (string)null);
                });

            modelBuilder.Entity("Railway.Api.Models.Cargocontainer", b =>
                {
                    b.HasOne("Railway.Api.Models.Freightshipment", "Shipment")
                        .WithMany("Cargocontainers")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("cargocontainer_ibfk_1");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("Railway.Api.Models.Customsclearance", b =>
                {
                    b.HasOne("Railway.Api.Models.Freightshipment", "Shipment")
                        .WithMany("Customsclearances")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("customsclearance_ibfk_1");

                    b.HasOne("Railway.Api.Models.Station", "Station")
                        .WithMany("Customsclearances")
                        .HasForeignKey("StationId")
                        .IsRequired()
                        .HasConstraintName("customsclearance_ibfk_2");

                    b.Navigation("Shipment");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Railway.Api.Models.Dependent", b =>
                {
                    b.HasOne("Railway.Api.Models.Passenger", "Passenger")
                        .WithMany("Dependents")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("dependent_ibfk_1");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("Railway.Api.Models.Freightshipment", b =>
                {
                    b.HasOne("Railway.Api.Models.Freighttrain", "Train")
                        .WithMany("Freightshipments")
                        .HasForeignKey("TrainId")
                        .IsRequired()
                        .HasConstraintName("freightshipment_ibfk_1");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("Railway.Api.Models.Freighttrain", b =>
                {
                    b.HasOne("Railway.Api.Models.Train", "Train")
                        .WithOne("Freighttrain")
                        .HasForeignKey("Railway.Api.Models.Freighttrain", "TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("freighttrain_ibfk_1");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("Railway.Api.Models.Loyaltyaccount", b =>
                {
                    b.HasOne("Railway.Api.Models.Passenger", "Passenger")
                        .WithOne("Loyaltyaccount")
                        .HasForeignKey("Railway.Api.Models.Loyaltyaccount", "PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("loyaltyaccount_ibfk_1");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("Railway.Api.Models.Luggage", b =>
                {
                    b.HasOne("Railway.Api.Models.Reservation", "Reservation")
                        .WithMany("Luggage")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("luggage_ibfk_1");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Railway.Api.Models.Maintenancerecord", b =>
                {
                    b.HasOne("Railway.Api.Models.Tracksegment", "Track")
                        .WithMany("Maintenancerecords")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("maintenancerecord_ibfk_2");

                    b.HasOne("Railway.Api.Models.Train", "Train")
                        .WithMany("Maintenancerecords")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("maintenancerecord_ibfk_1");

                    b.Navigation("Track");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("Railway.Api.Models.Passengertrain", b =>
                {
                    b.HasOne("Railway.Api.Models.Train", "Train")
                        .WithOne("Passengertrain")
                        .HasForeignKey("Railway.Api.Models.Passengertrain", "TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("passengertrain_ibfk_1");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("Railway.Api.Models.Reservation", b =>
                {
                    b.HasOne("Railway.Api.Models.Passenger", "Passenger")
                        .WithMany("Reservations")
                        .HasForeignKey("PassengerId")
                        .IsRequired()
                        .HasConstraintName("reservation_ibfk_1");

                    b.HasOne("Railway.Api.Models.Trainschedule", "Schedule")
                        .WithMany("Reservations")
                        .HasForeignKey("ScheduleId")
                        .IsRequired()
                        .HasConstraintName("reservation_ibfk_2");

                    b.Navigation("Passenger");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Railway.Api.Models.Routestop", b =>
                {
                    b.HasOne("Railway.Api.Models.Route", "Route")
                        .WithMany("Routestops")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("routestop_ibfk_1");

                    b.HasOne("Railway.Api.Models.Station", "Station")
                        .WithMany("Routestops")
                        .HasForeignKey("StationId")
                        .IsRequired()
                        .HasConstraintName("routestop_ibfk_2");

                    b.Navigation("Route");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Railway.Api.Models.Seat", b =>
                {
                    b.HasOne("Railway.Api.Models.Reservation", "Reservation")
                        .WithMany("Seats")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("seat_ibfk_1");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Railway.Api.Models.Sensor", b =>
                {
                    b.HasOne("Railway.Api.Models.Train", "Train")
                        .WithMany()
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Train");
                });

            modelBuilder.Entity("Railway.Api.Models.Staffassignment", b =>
                {
                    b.HasOne("Railway.Api.Models.Trainschedule", "Schedule")
                        .WithMany("Staffassignments")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("staffassignment_ibfk_2");

                    b.HasOne("Railway.Api.Models.Staff", "Staff")
                        .WithMany("Staffassignments")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("staffassignment_ibfk_1");

                    b.Navigation("Schedule");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Railway.Api.Models.Station", b =>
                {
                    b.HasOne("Railway.Api.Models.Country", "Country")
                        .WithMany("Stations")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("station_ibfk_1");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Railway.Api.Models.Tracksegment", b =>
                {
                    b.HasOne("Railway.Api.Models.Station", "EndStation")
                        .WithMany("TracksegmentEndStations")
                        .HasForeignKey("EndStationId")
                        .IsRequired()
                        .HasConstraintName("tracksegment_ibfk_2");

                    b.HasOne("Railway.Api.Models.Station", "StartStation")
                        .WithMany("TracksegmentStartStations")
                        .HasForeignKey("StartStationId")
                        .IsRequired()
                        .HasConstraintName("tracksegment_ibfk_1");

                    b.Navigation("EndStation");

                    b.Navigation("StartStation");
                });

            modelBuilder.Entity("Railway.Api.Models.Trainschedule", b =>
                {
                    b.HasOne("Railway.Api.Models.Route", "Route")
                        .WithMany("Trainschedules")
                        .HasForeignKey("RouteId")
                        .IsRequired()
                        .HasConstraintName("trainschedule_ibfk_2");

                    b.HasOne("Railway.Api.Models.Train", "Train")
                        .WithMany("Trainschedules")
                        .HasForeignKey("TrainId")
                        .IsRequired()
                        .HasConstraintName("trainschedule_ibfk_1");

                    b.Navigation("Route");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("Railway.Api.Models.Waitinglist", b =>
                {
                    b.HasOne("Railway.Api.Models.Passenger", "Passenger")
                        .WithMany("Waitinglists")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("waitinglist_ibfk_1");

                    b.HasOne("Railway.Api.Models.Trainschedule", "Schedule")
                        .WithMany("Waitinglists")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("waitinglist_ibfk_2");

                    b.Navigation("Passenger");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Railway.Api.Models.Country", b =>
                {
                    b.Navigation("Stations");
                });

            modelBuilder.Entity("Railway.Api.Models.Freightshipment", b =>
                {
                    b.Navigation("Cargocontainers");

                    b.Navigation("Customsclearances");
                });

            modelBuilder.Entity("Railway.Api.Models.Freighttrain", b =>
                {
                    b.Navigation("Freightshipments");
                });

            modelBuilder.Entity("Railway.Api.Models.Passenger", b =>
                {
                    b.Navigation("Dependents");

                    b.Navigation("Loyaltyaccount");

                    b.Navigation("Reservations");

                    b.Navigation("Waitinglists");
                });

            modelBuilder.Entity("Railway.Api.Models.Reservation", b =>
                {
                    b.Navigation("Luggage");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Railway.Api.Models.Route", b =>
                {
                    b.Navigation("Routestops");

                    b.Navigation("Trainschedules");
                });

            modelBuilder.Entity("Railway.Api.Models.Staff", b =>
                {
                    b.Navigation("Staffassignments");
                });

            modelBuilder.Entity("Railway.Api.Models.Station", b =>
                {
                    b.Navigation("Customsclearances");

                    b.Navigation("Routestops");

                    b.Navigation("TracksegmentEndStations");

                    b.Navigation("TracksegmentStartStations");
                });

            modelBuilder.Entity("Railway.Api.Models.Tracksegment", b =>
                {
                    b.Navigation("Maintenancerecords");
                });

            modelBuilder.Entity("Railway.Api.Models.Train", b =>
                {
                    b.Navigation("Freighttrain");

                    b.Navigation("Maintenancerecords");

                    b.Navigation("Passengertrain");

                    b.Navigation("Trainschedules");
                });

            modelBuilder.Entity("Railway.Api.Models.Trainschedule", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("Staffassignments");

                    b.Navigation("Waitinglists");
                });
#pragma warning restore 612, 618
        }
    }
}
